[package]
name = "RustSGXQuoteGenerationSample"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sgx-dcap-ql-rs = { path = "../../QuoteGeneration/quote_wrapper/sgx-dcap-ql-rs"}
structopt = "0.3"
